version: "3.8"

services:
  # Gogs Server
  gogs:
    container_name: gogs
    image: "gogs/gogs:0.12.9"
    restart: always
    ports:
      - "${FORWARD_SSH_PORT:-1022}:22"
      - "${FORWARD_APP_PORT:-3000}:3000"
    volumes:
      - ./data/gogs:/data
    depends_on:
      db:
        condition: service_healthy
    networks:
      - gogs

  # MySQL Storage
  db:
    container_name: db
    image: 'mysql/mysql-server:5.7.38'
    volumes:
      - ./my.cnf:/etc/my.cnf      
      - ./data/mysql:/var/lib/mysql
      - ./data/logs/mysql:/var/log/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - "${FORWARD_DB_PORT:-33060}:3306"
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s
    networks:
      - gogs

# Docker Networks
networks:
  gogs:
    driver: bridge
