version: "3"
services:
  gogs-mysql:
    container_name: gogs-mysql
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql
      - /var/run/docker.sock:/var/run/docker.sock
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_password
      MYSQL_DATABASE: gogs
      MYSQL_USER: gogs
      MYSQL_PASSWORD: gogs_password

  gogs-server:
    container_name: gogs-server
    image: gogs/gogs:latest
    restart: always
    ports:
      - 1022:22
      - 3000:3000
    volumes:
      - ./data/gogs:/data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - gogs-mysql

networks:
  gogs-server:
    driver: bridge
